version: '2'
services:
  traefik:
    container_name: traefik
    image: traefik:1.7
    restart: unless-stopped
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
networks:
  web:
    external: true          
